// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProdFloor.Models;

namespace ProdFloor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210304165532_ShippingOnPlanningAdded")]
    partial class ShippingOnPlanningAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProdFloor.Models.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FirecodeID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("StateID");

                    b.HasKey("CityID");

                    b.HasIndex("FirecodeID");

                    b.HasIndex("StateID");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("ProdFloor.Models.City_audit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffectedItemID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<string>("Statement");

                    b.HasKey("ID");

                    b.ToTable("City_Audits");
                });

            modelBuilder.Entity("ProdFloor.Models.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("CountryID");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("ProdFloor.Models.Country_audit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffectedItemID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<string>("Statement");

                    b.HasKey("ID");

                    b.ToTable("Country_Audits");
                });

            modelBuilder.Entity("ProdFloor.Models.CustomFeature", b =>
                {
                    b.Property<int>("CustomFeatureID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomSoftwareID");

                    b.Property<int>("JobID");

                    b.HasKey("CustomFeatureID");

                    b.HasIndex("CustomSoftwareID");

                    b.HasIndex("JobID");

                    b.ToTable("CustomFeatures");
                });

            modelBuilder.Entity("ProdFloor.Models.CustomSoftware", b =>
                {
                    b.Property<int>("CustomSoftwareID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.HasKey("CustomSoftwareID");

                    b.ToTable("CustomSoftwares");
                });

            modelBuilder.Entity("ProdFloor.Models.DoorOperator", b =>
                {
                    b.Property<int>("DoorOperatorID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("DoorOperatorID");

                    b.ToTable("DoorOperators");
                });

            modelBuilder.Entity("ProdFloor.Models.DoorOperator_audit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffectedItemID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<string>("Statement");

                    b.HasKey("ID");

                    b.ToTable("DoorOperator_Audits");
                });

            modelBuilder.Entity("ProdFloor.Models.Element", b =>
                {
                    b.Property<int>("ElementID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CRO");

                    b.Property<bool>("CReg");

                    b.Property<bool>("CSD");

                    b.Property<bool>("CTF");

                    b.Property<bool>("CTINSPST");

                    b.Property<bool>("CTL");

                    b.Property<bool>("CallEnable");

                    b.Property<int>("Capacity");

                    b.Property<bool>("CarCardReader");

                    b.Property<bool>("CarKey");

                    b.Property<bool>("DHLD");

                    b.Property<string>("DoorGate")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("DoorOperatorID");

                    b.Property<bool>("EMT");

                    b.Property<bool>("EP");

                    b.Property<bool>("EQ");

                    b.Property<bool>("Egress");

                    b.Property<bool>("FRON2");

                    b.Property<int>("Frequency");

                    b.Property<bool>("HAPS");

                    b.Property<bool>("HCRO");

                    b.Property<bool>("HallCardReader");

                    b.Property<bool>("HallKey");

                    b.Property<string>("INA")
                        .IsRequired();

                    b.Property<bool>("INCP");

                    b.Property<int>("JobID");

                    b.Property<bool>("LJ");

                    b.Property<bool>("LOS");

                    b.Property<int>("LandingSystemID");

                    b.Property<string>("LoadWeigher")
                        .IsRequired();

                    b.Property<bool>("PFGE");

                    b.Property<bool>("PHECutOut");

                    b.Property<bool>("PSS");

                    b.Property<bool>("PTFLD");

                    b.Property<int>("Phase");

                    b.Property<int>("Speed");

                    b.Property<bool>("Traveler");

                    b.Property<bool>("VCI");

                    b.Property<int>("Voltage");

                    b.HasKey("ElementID");

                    b.HasIndex("DoorOperatorID");

                    b.HasIndex("JobID");

                    b.HasIndex("LandingSystemID");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("ProdFloor.Models.ElementHydro", b =>
                {
                    b.Property<int>("ElementHydroID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("FLA");

                    b.Property<float>("HP");

                    b.Property<int>("JobID");

                    b.Property<int>("SPH");

                    b.Property<string>("Starter")
                        .IsRequired();

                    b.Property<string>("ValveBrand")
                        .IsRequired();

                    b.HasKey("ElementHydroID");

                    b.HasIndex("JobID");

                    b.ToTable("ElementHydros");
                });

            modelBuilder.Entity("ProdFloor.Models.ElementTraction", b =>
                {
                    b.Property<int>("ElementTractionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contact")
                        .IsRequired();

                    b.Property<float>("Current");

                    b.Property<bool>("Encoder");

                    b.Property<float>("FLA");

                    b.Property<float>("HP");

                    b.Property<int>("HoldVoltage");

                    b.Property<bool>("ISO");

                    b.Property<int>("JobID");

                    b.Property<string>("MachineLocation")
                        .IsRequired();

                    b.Property<string>("MotorBrand")
                        .IsRequired();

                    b.Property<int>("PickVoltage");

                    b.Property<int>("Resistance");

                    b.Property<string>("VVVF")
                        .IsRequired();

                    b.HasKey("ElementTractionID");

                    b.HasIndex("JobID");

                    b.ToTable("ElementTractions");
                });

            modelBuilder.Entity("ProdFloor.Models.FireCode", b =>
                {
                    b.Property<int>("FireCodeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("FireCodeID");

                    b.ToTable("FireCodes");
                });

            modelBuilder.Entity("ProdFloor.Models.FireCode_audit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffectedItemID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<string>("Statement");

                    b.HasKey("ID");

                    b.ToTable("FireCode_Audits");
                });

            modelBuilder.Entity("ProdFloor.Models.GenericFeatures", b =>
                {
                    b.Property<int>("GenericFeaturesID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Attendant");

                    b.Property<bool>("BSI");

                    b.Property<bool>("BottomAccess");

                    b.Property<string>("BottomAccessLocation")
                        .HasMaxLength(25);

                    b.Property<bool>("CRO");

                    b.Property<bool>("CTINSPST");

                    b.Property<bool>("CallEnable");

                    b.Property<string>("CarCallCodeSecurity")
                        .HasMaxLength(50);

                    b.Property<bool>("CarCallRead");

                    b.Property<bool>("CarKey");

                    b.Property<bool>("CarToLobby");

                    b.Property<bool>("EMT");

                    b.Property<bool>("EP");

                    b.Property<string>("EPCarsNumber");

                    b.Property<string>("EPContact")
                        .HasMaxLength(50);

                    b.Property<bool>("EPOtherCars");

                    b.Property<bool>("EPSelect");

                    b.Property<bool>("EPVoltage");

                    b.Property<bool>("EQ");

                    b.Property<bool>("FLO");

                    b.Property<bool>("FRON2");

                    b.Property<string>("GovModel")
                        .HasMaxLength(50);

                    b.Property<bool>("HCRO");

                    b.Property<bool>("HallCallRead");

                    b.Property<bool>("HallKey");

                    b.Property<bool>("Hosp");

                    b.Property<bool>("INA");

                    b.Property<bool>("INCP");

                    b.Property<string>("INCPButtons")
                        .HasMaxLength(50);

                    b.Property<int>("JobID");

                    b.Property<bool>("LoadWeigher");

                    b.Property<string>("Monitoring")
                        .HasMaxLength(100);

                    b.Property<bool>("PTI");

                    b.Property<bool>("Pit");

                    b.Property<bool>("Roped");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(250);

                    b.Property<string>("SwitchStyle")
                        .HasMaxLength(50);

                    b.Property<bool>("TopAccess");

                    b.Property<string>("TopAccessLocation");

                    b.HasKey("GenericFeaturesID");

                    b.HasIndex("JobID")
                        .IsUnique();

                    b.ToTable("GenericFeaturesList");
                });

            modelBuilder.Entity("ProdFloor.Models.HoistWayData", b =>
                {
                    b.Property<int>("HoistWayDataID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity");

                    b.Property<int>("DownSpeed");

                    b.Property<bool>("FrontEightServed");

                    b.Property<bool>("FrontEleventhServed");

                    b.Property<bool>("FrontFifteenthServed");

                    b.Property<bool>("FrontFifthServed");

                    b.Property<bool>("FrontFirstServed");

                    b.Property<bool>("FrontFourteenthServed");

                    b.Property<bool>("FrontFourthServed");

                    b.Property<bool>("FrontNinthServed");

                    b.Property<bool>("FrontSecondServed");

                    b.Property<bool>("FrontSeventhServed");

                    b.Property<bool>("FrontSexthServed");

                    b.Property<bool>("FrontSixteenthServed");

                    b.Property<bool>("FrontTenthServed");

                    b.Property<bool>("FrontThirdServed");

                    b.Property<bool>("FrontThirteenthServed");

                    b.Property<bool>("FrontTwelvethServed");

                    b.Property<int>("HoistWaysNumber");

                    b.Property<int>("JobID");

                    b.Property<int>("LandingSystemID");

                    b.Property<int>("MachineRooms");

                    b.Property<bool>("RearEightServed");

                    b.Property<bool>("RearEleventhServed");

                    b.Property<bool>("RearFifteenthServed");

                    b.Property<bool>("RearFifthServed");

                    b.Property<bool>("RearFirstServed");

                    b.Property<bool>("RearFourteenthServed");

                    b.Property<bool>("RearFourthServed");

                    b.Property<bool>("RearNinthServed");

                    b.Property<bool>("RearSecondServed");

                    b.Property<bool>("RearSeventhServed");

                    b.Property<bool>("RearSexthServed");

                    b.Property<bool>("RearSixteenthServed");

                    b.Property<bool>("RearTenthServed");

                    b.Property<bool>("RearThirdServed");

                    b.Property<bool>("RearThirteenthServed");

                    b.Property<bool>("RearTwelvethServed");

                    b.Property<int>("TotalTravel");

                    b.Property<int>("UpSpeed");

                    b.HasKey("HoistWayDataID");

                    b.HasIndex("JobID")
                        .IsUnique();

                    b.HasIndex("LandingSystemID");

                    b.ToTable("HoistWayDatas");
                });

            modelBuilder.Entity("ProdFloor.Models.HydroSpecific", b =>
                {
                    b.Property<int>("HydroSpecificID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Battery");

                    b.Property<string>("BatteryBrand")
                        .HasMaxLength(50);

                    b.Property<float>("FLA");

                    b.Property<int>("HP");

                    b.Property<int>("JobID");

                    b.Property<bool>("LOS");

                    b.Property<bool>("LifeJacket");

                    b.Property<int>("MotorsDisconnect");

                    b.Property<int>("MotorsNum");

                    b.Property<bool>("OilCool");

                    b.Property<bool>("OilTank");

                    b.Property<bool>("PSS");

                    b.Property<bool>("Resync");

                    b.Property<int>("SPH");

                    b.Property<string>("Starter")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("VCI");

                    b.Property<string>("ValveBrand")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ValveCoils");

                    b.Property<int>("ValveNum");

                    b.Property<int>("ValveVoltage");

                    b.HasKey("HydroSpecificID");

                    b.HasIndex("JobID")
                        .IsUnique();

                    b.ToTable("HydroSpecifics");
                });

            modelBuilder.Entity("ProdFloor.Models.Indicator", b =>
                {
                    b.Property<int>("IndicatorID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarCallsType")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("CarCallsVoltage")
                        .IsRequired();

                    b.Property<string>("CarCallsVoltageType")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<bool>("CarLanterns");

                    b.Property<string>("CarLanternsStyle")
                        .HasMaxLength(25);

                    b.Property<string>("CarLanternsType")
                        .HasMaxLength(10);

                    b.Property<bool>("CarPI");

                    b.Property<string>("CarPIDiscreteType")
                        .HasMaxLength(25);

                    b.Property<string>("CarPIType")
                        .HasMaxLength(25);

                    b.Property<string>("HallCallsType")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("HallCallsVoltage")
                        .IsRequired();

                    b.Property<string>("HallCallsVoltageType")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<bool>("HallLanterns");

                    b.Property<string>("HallLanternsStyle")
                        .HasMaxLength(50);

                    b.Property<string>("HallLanternsType")
                        .HasMaxLength(10);

                    b.Property<bool>("HallPI");

                    b.Property<bool>("HallPIAll");

                    b.Property<string>("HallPIDiscreteType")
                        .HasMaxLength(25);

                    b.Property<string>("HallPIType")
                        .HasMaxLength(25);

                    b.Property<int>("IndicatorsVoltage");

                    b.Property<string>("IndicatorsVoltageType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("JobID");

                    b.Property<bool>("PassingFloor");

                    b.Property<string>("PassingFloorDiscreteType")
                        .HasMaxLength(25);

                    b.Property<bool>("PassingFloorEnable");

                    b.Property<string>("PassingFloorType")
                        .HasMaxLength(25);

                    b.Property<bool>("VoiceAnnunciationPI");

                    b.Property<string>("VoiceAnnunciationPIType")
                        .HasMaxLength(50);

                    b.HasKey("IndicatorID");

                    b.HasIndex("JobID")
                        .IsUnique();

                    b.ToTable("Indicators");
                });

            modelBuilder.Entity("ProdFloor.Models.Job", b =>
                {
                    b.Property<int>("JobID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityID");

                    b.Property<string>("Contractor")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("CrossAppEngID");

                    b.Property<string>("Cust")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("EngID");

                    b.Property<int>("FireCodeID");

                    b.Property<string>("JobNum");

                    b.Property<int>("JobTypeID");

                    b.Property<DateTime>("LatestFinishDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name2")
                        .HasMaxLength(50);

                    b.Property<DateTime>("ShipDate");

                    b.Property<string>("Status")
                        .HasMaxLength(26);

                    b.HasKey("JobID");

                    b.HasIndex("CityID");

                    b.HasIndex("FireCodeID");

                    b.HasIndex("JobTypeID");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("ProdFloor.Models.JobAdditional", b =>
                {
                    b.Property<int>("JobAdditionalID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action");

                    b.Property<DateTime>("ERDate");

                    b.Property<int>("JobID");

                    b.Property<int>("Priority");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.HasKey("JobAdditionalID");

                    b.HasIndex("JobID")
                        .IsUnique();

                    b.ToTable("JobAdditionals");
                });

            modelBuilder.Entity("ProdFloor.Models.JobExtension", b =>
                {
                    b.Property<int>("JobExtensionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AUXCOP");

                    b.Property<bool>("AltRis");

                    b.Property<bool>("BackUpDisp");

                    b.Property<bool>("CartopDoorButtons");

                    b.Property<string>("DoorGate")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("DoorHoist")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("DoorHold");

                    b.Property<int>("DoorOperatorID");

                    b.Property<bool>("HeavyDoors");

                    b.Property<bool>("InfDetector");

                    b.Property<int>("InputFrecuency");

                    b.Property<int>("InputPhase");

                    b.Property<int>("InputVoltage");

                    b.Property<int>("JobID");

                    b.Property<string>("JobTypeAdd")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("JobTypeMain")
                        .IsRequired()
                        .HasMaxLength(26);

                    b.Property<bool>("MechSafEdge");

                    b.Property<bool>("Nudging");

                    b.Property<int>("NumOfStops");

                    b.Property<bool>("SCOP");

                    b.Property<bool>("SHC");

                    b.Property<int>("SHCRisers");

                    b.Property<bool>("SwingOp");

                    b.HasKey("JobExtensionID");

                    b.HasIndex("DoorOperatorID");

                    b.HasIndex("JobID")
                        .IsUnique();

                    b.ToTable("JobsExtensions");
                });

            modelBuilder.Entity("ProdFloor.Models.JobType", b =>
                {
                    b.Property<int>("JobTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("JobTypeID");

                    b.ToTable("JobTypes");
                });

            modelBuilder.Entity("ProdFloor.Models.JobType_audit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffectedItemID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<string>("Statement");

                    b.HasKey("ID");

                    b.ToTable("JobType__Audits");
                });

            modelBuilder.Entity("ProdFloor.Models.LandingSystem", b =>
                {
                    b.Property<int>("LandingSystemID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("UsedIn")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("LandingSystemID");

                    b.ToTable("LandingSystems");
                });

            modelBuilder.Entity("ProdFloor.Models.LandingSystem_audit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffectedItemID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<string>("Statement");

                    b.HasKey("ID");

                    b.ToTable("LandingSystem_Audits");
                });

            modelBuilder.Entity("ProdFloor.Models.Overload", b =>
                {
                    b.Property<int>("OverloadID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("AMPMax");

                    b.Property<float>("AMPMin");

                    b.Property<string>("MCPart")
                        .IsRequired();

                    b.Property<int>("OverTableNum");

                    b.Property<string>("SiemensPart")
                        .IsRequired();

                    b.HasKey("OverloadID");

                    b.ToTable("Overloads");
                });

            modelBuilder.Entity("ProdFloor.Models.Overload_audit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffectedItemID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Statement");

                    b.HasKey("ID");

                    b.ToTable("Overload_Audits");
                });

            modelBuilder.Entity("ProdFloor.Models.PlanningReport", b =>
                {
                    b.Property<int>("PlanningReportID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Busy");

                    b.Property<DateTime>("DateTimeLoad");

                    b.Property<DateTime>("PlanningDate");

                    b.HasKey("PlanningReportID");

                    b.ToTable("PlanningReports");
                });

            modelBuilder.Entity("ProdFloor.Models.PlanningReportRow", b =>
                {
                    b.Property<int>("PlanningReportRowID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Consecutive");

                    b.Property<bool>("Custom");

                    b.Property<string>("JobName");

                    b.Property<string>("JobNumber");

                    b.Property<string>("MRP");

                    b.Property<string>("Material");

                    b.Property<string>("Notes");

                    b.Property<int>("PO");

                    b.Property<int>("PlanningReportID");

                    b.Property<string>("PreviousWorkCenter");

                    b.Property<string>("Priority");

                    b.Property<string>("ShippingDate");

                    b.Property<string>("SoldTo");

                    b.Property<string>("WorkCenter");

                    b.HasKey("PlanningReportRowID");

                    b.HasIndex("PlanningReportID");

                    b.ToTable("PlanningReportRows");
                });

            modelBuilder.Entity("ProdFloor.Models.PO", b =>
                {
                    b.Property<int>("POID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("JobID");

                    b.Property<int>("PONumb");

                    b.HasKey("POID");

                    b.HasIndex("JobID");

                    b.HasIndex("PONumb")
                        .IsUnique();

                    b.ToTable("POs");
                });

            modelBuilder.Entity("ProdFloor.Models.Reason1", b =>
                {
                    b.Property<int>("Reason1ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Reason1ID");

                    b.ToTable("Reasons1");
                });

            modelBuilder.Entity("ProdFloor.Models.Reason2", b =>
                {
                    b.Property<int>("Reason2ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("Reason1ID");

                    b.HasKey("Reason2ID");

                    b.HasIndex("Reason1ID");

                    b.ToTable("Reasons2");
                });

            modelBuilder.Entity("ProdFloor.Models.Reason3", b =>
                {
                    b.Property<int>("Reason3ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("Reason2ID");

                    b.HasKey("Reason3ID");

                    b.HasIndex("Reason2ID");

                    b.ToTable("Reasons3");
                });

            modelBuilder.Entity("ProdFloor.Models.Reason4", b =>
                {
                    b.Property<int>("Reason4ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("Reason3ID");

                    b.HasKey("Reason4ID");

                    b.HasIndex("Reason3ID");

                    b.ToTable("Reasons4");
                });

            modelBuilder.Entity("ProdFloor.Models.Reason5", b =>
                {
                    b.Property<int>("Reason5ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("Reason4ID");

                    b.HasKey("Reason5ID");

                    b.HasIndex("Reason4ID");

                    b.ToTable("Reasons5");
                });

            modelBuilder.Entity("ProdFloor.Models.Slowdown", b =>
                {
                    b.Property<int>("SlowdownID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("A");

                    b.Property<int>("CarSpeedFPM");

                    b.Property<int>("Distance");

                    b.Property<int>("MiniumFloorHeight");

                    b.Property<int>("SlowLimit");

                    b.HasKey("SlowdownID");

                    b.ToTable("Slowdowns");
                });

            modelBuilder.Entity("ProdFloor.Models.Slowdown_audit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffectedItemID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Statement");

                    b.HasKey("ID");

                    b.ToTable("Slowdown__Audits");
                });

            modelBuilder.Entity("ProdFloor.Models.SpecialFeatures", b =>
                {
                    b.Property<int>("SpecialFeaturesID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<int>("JobID");

                    b.HasKey("SpecialFeaturesID");

                    b.HasIndex("JobID");

                    b.ToTable("SpecialFeatures");
                });

            modelBuilder.Entity("ProdFloor.Models.Starter", b =>
                {
                    b.Property<int>("StarterID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("FLA");

                    b.Property<float>("HP");

                    b.Property<string>("MCPart")
                        .IsRequired();

                    b.Property<string>("NewManufacturerPart")
                        .IsRequired();

                    b.Property<string>("OverloadTable")
                        .IsRequired();

                    b.Property<string>("StarterType")
                        .IsRequired();

                    b.Property<string>("Volts")
                        .IsRequired();

                    b.HasKey("StarterID");

                    b.ToTable("Starters");
                });

            modelBuilder.Entity("ProdFloor.Models.Starter_audit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffectedItemID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Statement");

                    b.HasKey("ID");

                    b.ToTable("Starter_Audits");
                });

            modelBuilder.Entity("ProdFloor.Models.State", b =>
                {
                    b.Property<int>("StateID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("StateID");

                    b.HasIndex("CountryID");

                    b.ToTable("States");
                });

            modelBuilder.Entity("ProdFloor.Models.State_audit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffectedItemID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<string>("Statement");

                    b.HasKey("ID");

                    b.ToTable("State_Audits");
                });

            modelBuilder.Entity("ProdFloor.Models.Station", b =>
                {
                    b.Property<int>("StationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("JobTypeID");

                    b.Property<string>("Label");

                    b.HasKey("StationID");

                    b.HasIndex("JobTypeID");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("ProdFloor.Models.Step", b =>
                {
                    b.Property<int>("StepID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime>("ExpectedTime");

                    b.Property<int>("JobTypeID");

                    b.Property<int>("Order");

                    b.Property<string>("Stage")
                        .IsRequired();

                    b.HasKey("StepID");

                    b.HasIndex("JobTypeID");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("ProdFloor.Models.StepsForJob", b =>
                {
                    b.Property<int>("StepsForJobID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuxStationID");

                    b.Property<int>("AuxTechnicianID");

                    b.Property<bool>("Complete");

                    b.Property<int>("Consecutivo");

                    b.Property<DateTime>("Elapsed");

                    b.Property<bool>("Obsolete");

                    b.Property<DateTime>("Start");

                    b.Property<int>("StepID");

                    b.Property<DateTime>("Stop");

                    b.Property<int>("TestJobID");

                    b.HasKey("StepsForJobID");

                    b.HasIndex("StepID");

                    b.HasIndex("TestJobID");

                    b.ToTable("StepsForJobs");
                });

            modelBuilder.Entity("ProdFloor.Models.Stop", b =>
                {
                    b.Property<int>("StopID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuxStationID");

                    b.Property<int>("AuxTechnicianID");

                    b.Property<bool>("Critical");

                    b.Property<string>("Description");

                    b.Property<DateTime>("Elapsed");

                    b.Property<int>("Reason1");

                    b.Property<int>("Reason2");

                    b.Property<int>("Reason3");

                    b.Property<int>("Reason4");

                    b.Property<int>("Reason5ID");

                    b.Property<DateTime>("StartDate");

                    b.Property<DateTime>("StopDate");

                    b.Property<int>("TestJobID");

                    b.HasKey("StopID");

                    b.HasIndex("Reason5ID");

                    b.HasIndex("TestJobID");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("ProdFloor.Models.TestFeature", b =>
                {
                    b.Property<int>("TestFeatureID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BrakeCoilVoltageMoreThan10");

                    b.Property<bool>("CTL2");

                    b.Property<bool>("Cartop");

                    b.Property<bool>("Custom");

                    b.Property<bool>("EMBrake");

                    b.Property<bool>("EMCO");

                    b.Property<bool>("Group");

                    b.Property<bool>("Local");

                    b.Property<bool>("MRL");

                    b.Property<bool>("Overlay");

                    b.Property<bool>("PC");

                    b.Property<bool>("R6");

                    b.Property<bool>("ShortFloor");

                    b.Property<int>("TestJobID");

                    b.Property<bool>("TrajetaCPI");

                    b.HasKey("TestFeatureID");

                    b.HasIndex("TestJobID")
                        .IsUnique();

                    b.ToTable("TestFeatures");
                });

            modelBuilder.Entity("ProdFloor.Models.TestJob", b =>
                {
                    b.Property<int>("TestJobID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CompletedDate");

                    b.Property<int>("JobID");

                    b.Property<string>("JobLabel");

                    b.Property<int>("SinglePO");

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("StationID");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<int>("TechnicianID");

                    b.HasKey("TestJobID");

                    b.HasIndex("JobID");

                    b.ToTable("TestJobs");
                });

            modelBuilder.Entity("ProdFloor.Models.TriggeringCustSoft", b =>
                {
                    b.Property<int>("TriggeringCustSoftID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomSoftwareID");

                    b.Property<string>("Name");

                    b.Property<bool>("isSelected");

                    b.Property<string>("itemToMatch");

                    b.HasKey("TriggeringCustSoftID");

                    b.HasIndex("CustomSoftwareID");

                    b.ToTable("TriggeringCustSofts");
                });

            modelBuilder.Entity("ProdFloor.Models.TriggeringFeature", b =>
                {
                    b.Property<int>("TriggeringFeatureID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsSelected");

                    b.Property<string>("Name");

                    b.Property<int>("StepID");

                    b.HasKey("TriggeringFeatureID");

                    b.HasIndex("StepID");

                    b.ToTable("TriggeringFeatures");
                });

            modelBuilder.Entity("ProdFloor.Models.WireTypeSize_audit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffectedItemID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Statement");

                    b.HasKey("ID");

                    b.ToTable("WireTypeSize_Audits");
                });

            modelBuilder.Entity("ProdFloor.Models.WireTypesSize", b =>
                {
                    b.Property<int>("WireTypesSizeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AMPRating");

                    b.Property<string>("Size")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("WireTypesSizeID");

                    b.ToTable("WireTypesSizes");
                });

            modelBuilder.Entity("ProdFloor.Models.City", b =>
                {
                    b.HasOne("ProdFloor.Models.FireCode")
                        .WithMany("_Cities")
                        .HasForeignKey("FirecodeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProdFloor.Models.State")
                        .WithMany("_Cities")
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.CustomFeature", b =>
                {
                    b.HasOne("ProdFloor.Models.CustomSoftware")
                        .WithMany("_CustomFeatures")
                        .HasForeignKey("CustomSoftwareID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProdFloor.Models.Job")
                        .WithMany("_CustomFeatures")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.Element", b =>
                {
                    b.HasOne("ProdFloor.Models.DoorOperator")
                        .WithMany("_Elements")
                        .HasForeignKey("DoorOperatorID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProdFloor.Models.Job")
                        .WithMany("_Elements")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProdFloor.Models.LandingSystem")
                        .WithMany("_Elements")
                        .HasForeignKey("LandingSystemID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.ElementHydro", b =>
                {
                    b.HasOne("ProdFloor.Models.Job")
                        .WithMany("_ElementHydros")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.ElementTraction", b =>
                {
                    b.HasOne("ProdFloor.Models.Job")
                        .WithMany("_EmentTractions")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.GenericFeatures", b =>
                {
                    b.HasOne("ProdFloor.Models.Job")
                        .WithOne("_GenericFeatures")
                        .HasForeignKey("ProdFloor.Models.GenericFeatures", "JobID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.HoistWayData", b =>
                {
                    b.HasOne("ProdFloor.Models.Job")
                        .WithOne("_HoistWayData")
                        .HasForeignKey("ProdFloor.Models.HoistWayData", "JobID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProdFloor.Models.LandingSystem")
                        .WithMany("_HoistWayDatas")
                        .HasForeignKey("LandingSystemID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.HydroSpecific", b =>
                {
                    b.HasOne("ProdFloor.Models.Job")
                        .WithOne("_HydroSpecific")
                        .HasForeignKey("ProdFloor.Models.HydroSpecific", "JobID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.Indicator", b =>
                {
                    b.HasOne("ProdFloor.Models.Job")
                        .WithOne("_Indicator")
                        .HasForeignKey("ProdFloor.Models.Indicator", "JobID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.Job", b =>
                {
                    b.HasOne("ProdFloor.Models.City")
                        .WithMany("_Jobs")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProdFloor.Models.FireCode")
                        .WithMany("_Jobs")
                        .HasForeignKey("FireCodeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProdFloor.Models.JobType")
                        .WithMany("_Jobs")
                        .HasForeignKey("JobTypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.JobAdditional", b =>
                {
                    b.HasOne("ProdFloor.Models.Job")
                        .WithOne("_JobAdditional")
                        .HasForeignKey("ProdFloor.Models.JobAdditional", "JobID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.JobExtension", b =>
                {
                    b.HasOne("ProdFloor.Models.DoorOperator")
                        .WithMany("_JobExtensions")
                        .HasForeignKey("DoorOperatorID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProdFloor.Models.Job")
                        .WithOne("_jobExtension")
                        .HasForeignKey("ProdFloor.Models.JobExtension", "JobID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.PlanningReportRow", b =>
                {
                    b.HasOne("ProdFloor.Models.PlanningReport")
                        .WithMany("Rows")
                        .HasForeignKey("PlanningReportID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.PO", b =>
                {
                    b.HasOne("ProdFloor.Models.Job")
                        .WithMany("_PO")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.Reason2", b =>
                {
                    b.HasOne("ProdFloor.Models.Reason1")
                        .WithMany("_Reason2s")
                        .HasForeignKey("Reason1ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.Reason3", b =>
                {
                    b.HasOne("ProdFloor.Models.Reason2")
                        .WithMany("_Reason3s")
                        .HasForeignKey("Reason2ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.Reason4", b =>
                {
                    b.HasOne("ProdFloor.Models.Reason3")
                        .WithMany("_Reason4s")
                        .HasForeignKey("Reason3ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.Reason5", b =>
                {
                    b.HasOne("ProdFloor.Models.Reason4")
                        .WithMany("_Reason5s")
                        .HasForeignKey("Reason4ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.SpecialFeatures", b =>
                {
                    b.HasOne("ProdFloor.Models.Job", "Job")
                        .WithMany("_SpecialFeatureslist")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.State", b =>
                {
                    b.HasOne("ProdFloor.Models.Country")
                        .WithMany("_States")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.Station", b =>
                {
                    b.HasOne("ProdFloor.Models.JobType")
                        .WithMany("_Stations")
                        .HasForeignKey("JobTypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.Step", b =>
                {
                    b.HasOne("ProdFloor.Models.JobType")
                        .WithMany("Steps")
                        .HasForeignKey("JobTypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.StepsForJob", b =>
                {
                    b.HasOne("ProdFloor.Models.Step")
                        .WithMany("_StepsForJob")
                        .HasForeignKey("StepID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProdFloor.Models.TestJob")
                        .WithMany("_StepsForJobs")
                        .HasForeignKey("TestJobID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.Stop", b =>
                {
                    b.HasOne("ProdFloor.Models.Reason5")
                        .WithMany("_Stops")
                        .HasForeignKey("Reason5ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProdFloor.Models.TestJob")
                        .WithMany("_Stops")
                        .HasForeignKey("TestJobID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.TestFeature", b =>
                {
                    b.HasOne("ProdFloor.Models.TestJob")
                        .WithOne("_TestFeature")
                        .HasForeignKey("ProdFloor.Models.TestFeature", "TestJobID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.TestJob", b =>
                {
                    b.HasOne("ProdFloor.Models.Job")
                        .WithMany("_TestJobs")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.TriggeringCustSoft", b =>
                {
                    b.HasOne("ProdFloor.Models.CustomSoftware")
                        .WithMany("_TriggeringCustSofts")
                        .HasForeignKey("CustomSoftwareID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProdFloor.Models.TriggeringFeature", b =>
                {
                    b.HasOne("ProdFloor.Models.Step")
                        .WithMany("_TriggeringFeatures")
                        .HasForeignKey("StepID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
